package code

import (
	"fmt"
	"io"
)

const (
	appName = "go-codegen"
	repoUrl = "https://github.com/nchern/go-codegen"
)

// Generator defines interface that generates sources
type Generator interface {
	Generate(io.Writer) error
}

type bannerPrinter struct {
	decorated Generator
}

func (g *bannerPrinter) Generate(w io.Writer) error {
	_, err := fmt.Fprintf(w,
		"// generated by %s(%s)\n// You COULD edit this code it you really need it and know what are you doing\n\n",
		appName, repoUrl)
	if err != nil {
		return err
	}

	return g.decorated.Generate(w)
}

// WrapWithBannerPrinter wraps given generator with printer
func WrapWithBannerPrinter(g Generator) Generator {
	return &bannerPrinter{decorated: g}
}
